spring:
  config:
    import: optional:configserver:http://localhost:8889
  application:
    name: loans-service

user:
  service:
    url: http://localhost:8090


management:
  endpoints:
    web:
      exposure:
        include: "*"
