spring:
  config:
    import: optional:configserver:http://localhost:8889
  application:
    name: loans-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/loans_service_db  # Ensure this is your actual database name
    username: postgres                             # Database username
    password: password                             # Database password
  jpa:
    hibernate:
      ddl-auto: update                             # Use 'update' for schema updates without dropping
    database-platform: org.hibernate.dialect.PostgreSQLDialect
user:
  service:
    url: http://localhost:8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8676

