apiVersion: v1
kind: ConfigMap
metadata:
  name: loans-service-config
  namespace: fintech
data:
  application.yml: |-
    spring:
      application:
        name: loans-service
      config:
        import: optional:configserver:http://config-service:8889
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update
    
    server:
      port: 8097
    
    management:
      endpoints:
        web:
          exposure:
            include: "*"
          base-path: /actuator
      endpoint:
        health:
          enabled: true
          probes:
            enabled: true
          show-details: always




      